events {
    worker_connections 1024; #handles 1024 active connections at a time
}


http{	
	server {

	    listen 443 ssl;

	    # Domain name this server responds to
	    server_name nalayyou.42.fr;

	    # TLS certificate
	    ssl_certificate /etc/ssl/certs/nginx-selfsigned.crt;

	    # Private key we generated
	    ssl_certificate_key /etc/ssl/private/nginx-selfsigned.key;

	    # allowed tls versions
	    ssl_protocols TLSv1.2 TLSv1.3;

	    # Directory containing the WordPress files
	    root /var/www/html;

	    # Default files to look for when a directory is requested
	    index index.php index.html;

	    # catch all (default)
	    location / {
		# look in each of them in order
		try_files $uri $uri/ /index.php?$args;
	    }

	    # regex for all files ending with php
	    location ~ \.php$ {

		# Load FastCGI parameters
		include fastcgi_params;

		# Send PHP requests to the WordPress container
		fastcgi_pass wordpress:9000;

		# Tell PHP-FPM exactly which PHP file to execute
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param HTTPS on;
		fastcgi_param HTTP_HOST $http_host;
	    }

	}
}
